language: php

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=master; PHPUNIT=6.5.*; SMW=~3.0@dev
      php: 7.1
    - env: DB=sqlite; MW=REL1_31; SMW=~3.0;
      php: 7.0
    - env: DB=sqlite; MW=REL1_31; SMW=~3.0@dev
      php: 7.0
    - env: DB=mysql; MW=REL1_32; SMW=~3.0@dev
      php: 7.2
    - env: DB=postgres; MW=REL1_33; SMW=~3.0@dev; TYPE=coverage
      php: 7.2
  allow_failures:
    # Broken due to https://phabricator.wikimedia.org/T188840
    - env: DB=mysql; MW=master; PHPUNIT=6.5.*; SMW=~3.0@dev

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-tasks.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - if [[ "$TYPE" != "coverage" ]]; then exit 0; fi
  - tests/phpunit/phpunit.php -c extensions/SemanticTasks/phpunit.xml.dist --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
